version: "3"

services:
  database:
    image: postgres:15.2-alpine
    container_name: postgres-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: javadb
